//> using publish.organization "org.virtuslab"
//> using publish.name "typed-frames"
//> using publish.computeVersion "git:tag"
//> using publish.url "https://github.com/VirtusLab/typed-frames"
//> using publish.versionControl "scm:git:github.com/VirtusLab/typed-frames.git"
//> using publish.license "Apache-2.0"
//> using publish.repository "central"
//> using publish.developer "prolativ|Michał Pałka|https://github.com/prolativ"