//> using publish.organization "org.virtuslab"
//> using publish.name "iskra"
//> using publish.computeVersion "git:tag"
//> using publish.url "https://github.com/VirtusLab/iskra"
//> using publish.versionControl "github:VirtusLab/iskra"
//> using publish.license "Apache-2.0"
//> using publish.repository "central"
//> using publish.developer "prolativ|Michał Pałka|https://github.com/prolativ"
